version: "3"
services:
  node-app:
    restart: always

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "5000:8080"

    volumes:
      - /app/node_modules
      - .:/app

    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
